apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
data:
  ASPNETCORE_URLS: http://+:8080
  RabbitMq__Host: rabbitmq
  RabbitMq__Port: "5672"
  RabbitMQ__Exchange: "fiap-cloud-games.exchange"
  Jwt__Issuer: FiapCloudGames.Users.API
  Jwt__Audience: ClientFiapCloudGames
