apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
stringData:
  RabbitMq__Username: guest
  RabbitMq__Password: guest
  Jwt__Secret: "KkR.cX]N=8Y3=%uqJJgPD+}K^f?cKnmchVFm-qfa3rUBjBU!G^1L8cn1nEvhv+*"
  ConnectionStrings__DefaultConnection: "Server=users-sqlserver,1433;Database=FiapCloudGamesUsers;User Id=sa;Password=Users!Passw0rd;TrustServerCertificate=True"
